---
  #--------------------------------------------------------------------
  # Configure git
  #--------------------------------------------------------------------  
  - name: Configure git
    command: "{{ item }}" 

    with_items:
    - git config --global push.default simple
    - git config --global diff.tool meld
    - git config --global difftool.meld.path "/usr/bin/meld"
    - git config --global difftool.prompt false
    - git config --global merge.tool meld
    - git config --global mergetool.meld.path "/usr/bin/meld"
    - git config --global mergetool.prompt false
    - git config --global core.autocrlf false
    - git config --global core.editor {{packages_dir}}/sublime
    changed_when: false
    become_user: "{{user}}"