---
  #--------------------------------------------------------------------
  # Sublime Download, Install, Configure
  #--------------------------------------------------------------------
  - name: Install apt-key for sublime-text
    apt_key: url=https://download.sublimetext.com/sublimehq-pub.gpg state=present

  - name: Make sure apt can work with https sources
    apt: update_cache=no name=apt-transport-https install_recommends=yes
  
  - name: Install sublime
    apt: update_cache=yes name=sublime-text install_recommends=yes

  - name: Select dev channel for sublime-text updates
    command: echo "deb https://download.sublimetext.com/ apt/dev/" > /etc/apt/sources.list.d/sublime-text.list
    changed_when: false

  - name: Setup Sublime Text Symlink
    file: src=/usr/bin/subl dest={{packages_dir}}/sublime state=link
