---

# MIT License
#
# Copyright (c) 2016 Jake Swart
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# To run: ansible-playbook environment.yaml --ask-become-pass
- hosts: localhost
  roles:
    - role: geerlingguy.git
  vars:
    git_install_from_source: true
    git_install_from_source_force_update: true
    KEYS:         "/secure/keys"
    PASS:         "/secure/pass"
    HOME:         "{{ lookup('env', 'HOME') }}"
    DOWN:         "{{HOME}}/Downloads"
    ALIAS:        "{{HOME}}/.bash_aliases"
    OPT_BIN:      "/opt/bin"
    CHROMIUM:     "chrome-linux.zip"
    SUBLIME:      "sublime_text_3_build_3125_x64.tar.bz2"
    ECLIPSE:      "eclipse-jee-neon-1a-linux-gtk-x86_64.tar.gz"
    JMETER_MAJOR: "3.1"
    JMETER:       "apache-jmeter-{{JMETER_MAJOR}}.tgz"
  become: yes
  become_user: root


  #-----------------------------------------------------------------------
  # Setup the Bare Minimum to Run Ansible on a Target Machine
  #-----------------------------------------------------------------------
  # Kludges for for Ubuntu 14.04.
  # TODO: Needs to be retested
  pre_tasks:

    - block:
      - raw: sudo apt-get -y install python-simplejson
        changed_when: false
        when: ansible_distribution == 'Ubuntu'
      - raw: sudo apt-get -y install python-dev
        changed_when: false
      - raw: sudo apt-get -y install python-setuptools
        changed_when: false

      - name: Install pip
        raw: sudo easy_install pip
        changed_when: false

      - name: Install python-apt
        raw: sudo apt-get -y install python-apt
        changed_when: false
      when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "14.04"

  tasks:

  #-----------------------------------------------------------------------
  # Setup Common Environment (Dirs, Alaises, Env Vars)
  #-----------------------------------------------------------------------
  - name: Create {{OPT_BIN}}...
    file: path={{OPT_BIN}} state=directory mode=0775
    become: yes
    become_user: root

  # I cannot depend on lineinfile to "do what I expect". Everytime I use a regex, it replaces the line.
  # I just want it to replace the line if it's missing. This seems to do the job:
  - lineinfile: "dest={{HOME}}/.bashrc state=present insertafter=EOF line='# Add {{OPT_BIN}} to PATH'"
  - lineinfile: "dest={{HOME}}/.bashrc state=present insertafter=EOF line='export PATH=$PATH:{{OPT_BIN}}'"
  - lineinfile: "dest={{HOME}}/.bashrc state=present insertafter=EOF line='source {{HOME}}/.bash_aliases'"

  - name: Add alias srccmds
    lineinfile: dest={{HOME}}/.bash_aliases state=present insertafter=EOF create=True
      line="alias srccmds='source ~/.bashrc'"
      regexp="^alias srccmds='source ~/.bashrc'$"

  - lineinfile: dest={{HOME}}/.bash_aliases state=present insertafter=EOF create=True
      line="alias editcmds='sublime ~/.bashrc ~/.bash_aliases'"
      regexp="^alias editcmds='sublime ~/.bashrc ~/.bash_aliases'$"

  - lineinfile: dest={{HOME}}/.bash_aliases state=present insertafter=EOF create=True
      line="alias h='history'"
      regexp="^alias h='history'$"

  - name: Setup Keys Dir
    file: path={{ KEYS }} state=directory mode=0700

  - name: Setup Pass Dir
    file: path={{ PASS }} state=directory mode=0700

  #-----------------------------------------------------------------------
  # Install Ansible Required Software
  #-----------------------------------------------------------------------
  - name: Install passlib
    pip: name=passlib

  - name: Update apt-get Cache
    apt: update_cache=yes install_recommends=yes
    changed_when: false

  - name: Install libssl-dev
    apt: update_cache=no name=libssl-dev install_recommends=yes

  - name: Install cryptography
    pip: name=cryptography

  #--------------------------------------------------------------------
  # Install Generic Software Packages
  #--------------------------------------------------------------------
  - name: Install vim
    apt: update_cache=no name=vim install_recommends=yes

  - name: Install meld
    apt: update_cache=no name=meld install_recommends=yes

  - name: Install gnupg2
    apt: update_cache=no name=gnupg2 install_recommends=yes

  # Source chromium doesn't work out of the box with Mint. See commit-
  # dfcbbcb for downloading the latest x64 chrome. Something about cake
  # and eating it... let's just go back to apt-get.
  - name: Install chromium-browser
    apt: update_cache=no name=chromium-browser install_recommends=yes

  #--------------------------------------------------------------------
  # Sublime Download, Install, Configure
  #--------------------------------------------------------------------
  - stat: path={{OPT_BIN}}/sublime
    register: stSublime

  - block:

    - name: Prevent Redownload
      stat: path={{DOWN}}/{{SUBLIME}}
      register: stDownSublime

    - name: Download Sublime Text
      get_url: dest={{DOWN}} url=https://download.sublimetext.com/{{SUBLIME}}
      when: stDownSublime.stat.exists is defined and not stDownSublime.stat.exists

    - name: Extract Sublime Text
      unarchive: src={{DOWN}}/{{SUBLIME}} dest=/opt

    - name: Setup Sublime Text Symlink
      file: src=/opt/sublime_text_3/sublime_text dest={{OPT_BIN}}/sublime state=link

    when: stSublime.stat.exists is defined and not stSublime.stat.exists

  #--------------------------------------------------------------------
  # Install JDK 8
  #--------------------------------------------------------------------
  - name: Install openjdk-r ppa
    command: add-apt-repository ppa:openjdk-r/ppa -y
    register: openjdk
    when: false

  - name: Update apt-get cache
    apt: update_cache=yes install_recommends=yes
    changed_when: false

  - name: Install openjdk-8-jdk
    apt: name=openjdk-8-jdk install_recommends=yes

  - name: Get path of Java 1.8
    shell: "update-java-alternatives -l | grep '1.8' | awk '{print $3}'"
    register: javaPath
    changed_when: false

  - name: Set JDK 8 as Default
    command: update-java-alternatives -s {{javaPath.stdout}}
    changed_when: false

  #--------------------------------------------------------------------
  # Eclipse Download, Install, Configure
  #--------------------------------------------------------------------
  - stat: path={{OPT_BIN}}/eclipse
    register: stEclipse

  - block:

    - name: Prevent Redownload
      stat: path={{DOWN}}/{{ECLIPSE}}
      register: stDownEclipse

    - name: Download Eclipse - Java EE
      get_url: dest={{DOWN}} url="https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/neon/1a/{{ECLIPSE}}&mirror_id=1"
      when: stDownEclipse.stat.exists is defined and not stDownEclipse.stat.exists

    - name: Extract Eclipse
      unarchive: src={{DOWN}}/{{ECLIPSE}} dest=/opt

    - name: Setup Eclipse Symlink
      file: src=/opt/eclipse/eclipse dest={{OPT_BIN}}/eclipse state=link

    - name: Install Eclipse Plugin - Shell Script Editor
      shell: "{{OPT_BIN}}/eclipse -nosplash -application org.eclipse.equinox.p2.director -repository https://download.eclipse.org/releases/neon/,https://download.eclipse.org/technology/dltk/updates/,https://sourceforge.net/projects/shelled/files/shelled/update/ -installIU net.sourceforge.shelled.feature.group"

    - name: Install Eclipse Plugin - YAML Editor
      shell: "{{OPT_BIN}}/eclipse -nosplash -application org.eclipse.equinox.p2.director -repository https://dadacoalition.org/yedit -installIU org.dadacoalition.yedit.feature.feature.group"

    when: stEclipse.stat.exists is defined and not stEclipse.stat.exists

  #--------------------------------------------------------------------
  # JMeter Download, Install, Verify, Configure
  #--------------------------------------------------------------------
  - stat: path={{OPT_BIN}}/jmeter
    register: stJmeter

  - block:

    - name: Prevent Redownload
      stat: path={{DOWN}}/{{JMETER}}
      register: stDownjmeter

    - name: Download jmeter
      get_url: dest={{DOWN}} url="https://mirror.its.dal.ca/apache//jmeter/binaries/{{JMETER}}"
      when: stDownjmeter.stat.exists is defined and not stDownjmeter.stat.exists

    - name: Download jmeter PGP
      get_url: dest={{DOWN}} url="https://www.apache.org/dist/jmeter/binaries/{{JMETER}}.asc"
      when: stDownjmeter.stat.exists is defined and not stDownjmeter.stat.exists

    - name: Authenticate jmeter - Get PGP Key
      command: gpg --keyserver pgpkeys.mit.edu --recv-key 0612B399
      register: recdKey

      # gpg --export 3B4FE6ACC0B21F32 | apt-key add --

    - name: Authenticate jmeter - Verify Key (trust network is not confirmed)
      command: gpg --verify {{DOWN}}/{{JMETER}}.asc {{DOWN}}/{{JMETER}}
      register: verkey

    - name: Extract jmeter
      unarchive: src={{DOWN}}/{{JMETER}} dest=/opt
      when: recdKey|succeeded and verkey|succeeded
    
    - name: Add alias jmeter
      lineinfile: "dest={{HOME}}/.bashrc state=present insertafter=EOF line='# No GUI jmeter'"
    
    - lineinfile: dest={{HOME}}/.bashrc state=present insertafter=EOF create=True
        line='jm () { jmeter -n "$@"; }'
        regexp="^jm"

    - name: Setup jmeter Symlink
      file: src=/opt/apache-jmeter-{{JMETER_MAJOR}}/bin/jmeter dest={{OPT_BIN}}/jmeter state=link

    when: stJmeter.stat.exists is defined and not stJmeter.stat.exists


  

