---
  #-----------------------------------------------------------------------
  # Setup the Bare Minimum to Run Ansible on a Target Machine
  #-----------------------------------------------------------------------
  - block:
    - raw: sudo apt-get -y install python-simplejson
      changed_when: false
      when: ansible_distribution == 'Ubuntu'
    - raw: sudo apt-get -y install python-dev
      changed_when: false
    - raw: sudo apt-get -y install python-setuptools
      changed_when: false

    - name: Install pip
      raw: sudo easy_install pip
      changed_when: false

    - name: Install python-apt
      raw: sudo apt-get -y install python-apt
      changed_when: false
    when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "14.04"

  #-----------------------------------------------------------------------
  # Install Ansible Required Software
  #-----------------------------------------------------------------------

  - name: Update apt-get Cache
    apt: update_cache=yes install_recommends=yes
    changed_when: false

  - name: Install pip
    apt: update_cache=no name=python-pip install_recommends=yes
    changed_when: false

  - name: Install passlib
    pip: name=passlib

  - name: Install libssl-dev
    apt: update_cache=no name=libssl-dev install_recommends=yes

  - name: Install cryptography
    pip: name=cryptography