---
# To run: ansible-playbook environment.yaml --ask-become-pass
# TODO: Add GPG key checking where possible
# TODO: Add some better way to find the latest version URLs of SW below
- hosts: localhost
  vars:
    HOME:    "{{ lookup('env', 'HOME') }}"
    DOWN:    "{{ HOME }}/Downloads"
    ALIAS:   "{{ HOME }}/.bash_aliases"
    OPT_BIN: "/opt/bin"
    SUBLIME: "sublime_text_3_build_3125_x64.tar.bz2"
    ECLIPSE: "eclipse-jee-neon-1a-linux-gtk-x86_64.tar.gz"

  tasks:

  - name: Create {{ OPT_BIN }}...
    file: path={{ OPT_BIN }} state=directory mode=0775
    become: yes
    become_user: root

  # I cannot depend on lineinfile to "do what I expect". Everytime I use a regex, it replaces the line.
  # I just want it to replace the line if it's missing. This seems to do the job:
  - lineinfile: "dest={{ HOME }}/.bashrc state=present insertafter=EOF line='#Add {{ OPT_BIN }} to PATH'"
  - lineinfile: "dest={{ HOME }}/.bashrc state=present insertafter=EOF line='export PATH=$PATH:{{ OPT_BIN }}'"

  # Setup Aliases
  - name: Add alias srccmds
    lineinfile: dest={{ HOME }}/.bash_aliases state=present insertafter=EOF create=True
      line="alias srccmds='source ~/.bashrc'"
      regexp="^alias srccmds='source ~/.bashrc'$"

  - lineinfile: dest={{ HOME }}/.bash_aliases state=present insertafter=EOF create=True
      line="alias editcmds='sublime ~/.bashrc ~/.bash_aliases'"
      regexp="^alias editcmds='sublime ~/.bashrc ~/.bash_aliases'$"

  - lineinfile: dest={{ HOME }}/.bash_aliases state=present insertafter=EOF create=True
      line="alias h='history'"
      regexp="^alias h='history'$"
  
  - name: Install vim
    apt: update_cache=no name=vim install_recommends=yes
    become: true
    become_user: root 

  # Setup sublime
  - stat: path={{ OPT_BIN }}/sublime
    register: stSublime

  - block:
    
    # Check for redownload
    - stat: path={{ DOWN }}/{{ SUBLIME }}
      register: stDownSublime

    - name: Download Sublime Text - Java EE
      get_url: dest={{ DOWN }} url=http://download.sublimetext.com/{{ SUBLIME }}
      when: stDownSublime.stat.exists is defined and not stDownSublime.stat.exists

    - name: Extract Sublime Text
      unarchive: src={{ DOWN }}/{{ SUBLIME }} dest=/opt
      become: true
      become_user: root

    - name: Setup Sublime Text Symlink
      file: src=/opt/sublime_text_3/sublime_text dest={{ OPT_BIN }}/sublime state=link
      become: true
      become_user: root

    when: stSublime.stat.exists is defined and not stSublime.stat.exists
  
  # Setup Eclipse
  - stat: path={{ OPT_BIN }}/eclipse
    register: stEclipse

  - block:

    # Check for redownload
    - stat: path={{ DOWN }}/{{ ECLIPSE }}
      register: stDownEclipse

    - name: Download Eclipse - Java EE
      get_url: dest={{ DOWN }} url="http://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/neon/1a/{{ECLIPSE}}&mirror_id=1"
      when: stDownEclipse.stat.exists is defined and not stDownEclipse.stat.exists

    - name: Extract Eclipse
      unarchive: src={{ DOWN }}/{{eclipse}} dest=/opt
      become: true
      become_user: root

    - name: Setup Eclipse Symlink
      file: src=/opt/eclipse/eclipse dest={{ OPT_BIN }}/eclipse state=link
      become: true
      become_user: root

    - name: Install Eclipse Plugin - Shell Script Editor
      shell: "{{OPT_BIN}}/eclipse -nosplash -application org.eclipse.equinox.p2.director -repository http://download.eclipse.org/releases/neon/,http://download.eclipse.org/technology/dltk/updates/,https://sourceforge.net/projects/shelled/files/shelled/update/ -installIU net.sourceforge.shelled.feature.group"

    - name: Install Eclipse Plugin - YAML Editor
      shell: "{{OPT_BIN}}/eclipse -nosplash -application org.eclipse.equinox.p2.director -repository http://dadacoalition.org/yedit -installIU org.dadacoalition.yedit.feature.feature.group"

    when: stEclipse.stat.exists is defined and not stEclipse.stat.exists
